name: Docker Image CI

on:
  push:
    branches: [ dev-tasks ]
  pull_request:
    branches: [ dev-tasks ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DCKR_NAME}}
        password: ${{secrets.DCKR_TOKEN}}
        
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{secrets.DCKR_NAME}}:latest
